# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kl.fhir.dk.children
canonical: http://fhir.kl.dk/term
name: KLChildren
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build
publisher:
  name: Kommunernes Landsforening
  url: http://kl.dk

  dependencies:
  hl7.fhir.dk.core:
    uri: https://hl7.dk/fhir/core
    version: 2.1.0
  kl.dk.fhir.term: dev

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
