# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kl.dk.fhir.children
canonical: http://fhir.kl.dk/children
name: KLChildren
status: active
version: 2.0.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: Release #ci-build
publisher:
  name: Kommunernes Landsforening
  url: http://kl.dk

dependencies:
  hl7.fhir.dk.core:
    uri: https://hl7.dk/fhir/core
    version: 3.1.0
  kl.dk.fhir.term: 1.1.0

parameters:
  special-url: [http://snomed.info/sct, http://loinc.org]

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  Example: example.html