# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kl.dk.fhir.children
canonical: http://fhir.kl.dk/children
name: KLChildren
title: "KLChildren implementation guide, an implementation of FBU"
description: "KLChildren contains the specification for reporting data from the Danish health promotion and disease prevention program for children in Denmark (Sundhedsplejen). Data is reported to FK Gateway"
status: active
version: 2.0.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: Release #ci-build
publisher:
  name: Kommunernes Landsforening
  url: http://kl.dk

dependencies:
  hl7.fhir.dk.core:
    uri: http://hl7.dk/fhir/core/ImplementationGuide/hl7.fhir.dk.core
    version: 3.2.0
  kl.dk.fhir.term: 2.0.0

parameters:
  special-url: [http://snomed.info/sct, http://loinc.org]

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  Example small children: example.html
  Example school children: example2.html